Estoque.Web/Areas/Admin/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Estoque.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class DefaultController : Controller
    {
        // GET: Admin/Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

Estoque.Web/Areas/Admin/Controllers/FornecedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Estoque.Web.Areas.Admin.Models;
using Estoque.DAL.Entity;
using Estoque.DAL.Persistence;

namespace Estoque.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class FornecedorController : Controller
    {
        // GET: Admin/Fornecedor
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastro()
        {
            return View();
        }

        public ActionResult Consulta()
        {
            return View();
        }

        public ActionResult Lista()
        {
            return View();
        }

        #region Metodos AJAX

        public JsonResult Cadastrar(FornecedorModelCadastro model)
        {
            try
            {
                Funcionario u = (Funcionario)Session["funcionariologado"];

                Fornecedor f = new Fornecedor();
                f.Nome = model.Nome;

                FornecedorDal d = new FornecedorDal();
                d.Insert(f);

                return Json("Dados gravados com sucesso.");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        public JsonResult Editar(FornecedorModelEdicao model)
        {
            try
            {
                Funcionario u = (Funcionario)Session["funcionariologado"];

                Fornecedor f = new Fornecedor();

                f.IdFornecedor = model.IdFornecedor;
                f.Nome = model.Nome;

                FornecedorDal d = new FornecedorDal();

                d.Update(f);

                return Json("Fornecedor atualizado.");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
   
        public JsonResult Consultar(FornecedorModelConsulta model)
        {
            try
            {
                Funcionario u = (Funcionario)Session["funcionariologado"];

                FornecedorDal d = new FornecedorDal();

                List<Fornecedor> list = new List<Fornecedor>();
                list.Add(d.FindById(model.IdFornecedor));

                return Json(list);

            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        public JsonResult Listar()
        {
            try
            {
                Funcionario u = (Funcionario)Session["funcionariologado"];

                FornecedorDal d = new FornecedorDal();

                List<Fornecedor> list = new List<Fornecedor>();
                list = d.FindAll();
                
                return Json(list);
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        public JsonResult Excluir(FornecedorModelExclusao model)
        {
            try
            {
                Funcionario u = (Funcionario)Session["funcionariologado"];

                FornecedorDal d = new FornecedorDal();

                d.Delete(model.IdFornecedor);

                return Json("Fornecedor Excluído.");
                
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
        #endregion
    }
}

Estoque.Web/Areas/Admin/Controllers/ProdutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Estoque.DAL.Entity;
using Estoque.DAL.Persistence;
using Estoque.Web.Areas.Admin.Models;

namespace Estoque.Web.Areas.Admin.Controllers
{
    [Authorize]
    public class ProdutoController : Controller
    {
        // GET: Admin/Produto
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastro()
        {
            return View();
        }

        public ActionResult Consulta()
        {
            return View();
        }

        public ActionResult Lista()
        {
            return View();
        }

        #region Metodos AJAX

        public JsonResult FillDropDownFornecedor()
        {
            FornecedorDal d = new FornecedorDal();

            var lista = d.FindAll();

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Cadastrar(ProdutoModelCadastro model)
        {
            try
            {
                Funcionario u = (Funcionario)Session["funcionariologado"];

                Produto p = new Produto();

                p.Nome = model.Nome;
                p.Preco = model.Preco;
                p.Quantidade = model.Quantidade;
                p.Descricao = model.Descricao;
                p.IdFornecedor = model.IdFornecedor;

                ProdutoDal d = new ProdutoDal();
                d.Insert(p);

                return Json("Dados gravados com sucesso.");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        public JsonResult Editar(ProdutoModelEdicao model)
        {
            try
            {
                Funcionario u = (Funcionario)Session["funcionariologado"];

                Produto p = new Produto();

                p.IdProduto = model.IdProduto;
                p.Nome = model.Nome;
                p.Preco = model.Preco;
                p.Quantidade = model.Quantidade;
                p.Descricao = model.Descricao;
                p.IdFornecedor = model.IdFornecedor;

                ProdutoDal d = new ProdutoDal();

                d.Update(p);

                return Json("Produto atualizado.");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        public JsonResult Consultar(ProdutoModelConsulta model)
        {
            try
            {
                Funcionario u = (Funcionario)Session["funcionariologado"];

                ProdutoDal d = new ProdutoDal();

                List<Produto> list = new List<Produto>();
                list.Add(d.FindById(model.IdProduto));

                return Json(list);

            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        public JsonResult Listar()
        {
            try
            {
                Funcionario u = (Funcionario)Session["funcionariologado"];

                ProdutoDal d = new ProdutoDal();

                List<Produto> list = new List<Produto>();
                list = d.FindAll();

                return Json(list);
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }

        public JsonResult Excluir(ProdutoModelExclusao model)
        {
            try
            {
                Funcionario u = (Funcionario)Session["funcionariologado"];

                ProdutoDal d = new ProdutoDal();

                d.Delete(model.IdProduto);

                return Json("Produto Excluído.");
            }
            catch (Exception e)
            {
                return Json(e.Message);
            }
        }
        #endregion
    }
}

Estoque.Web/Areas/Admin/Views/Shared/Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sistema de Estoque</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>

    @RenderSection("javascript", required: false)

</head>
<body>
    
    <div class="container">
        <div class="row">           
            <div class="panel panel-primary">
                <div class="panel-heading">
                    @Html.Partial("_PartialLogin")
                    <h3>Sistema de Estoque de Produtos</h3>
                </div>
                <ul class="nav nav-tabs">
                    <li>
                        <a href="@Url.Action("Index", "Default")">Home</a>
                    </li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Fornecedores<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Cadastro", "Fornecedor")">Cadastrar Fornecedor</a></li>
                            <li><a href="@Url.Action("Consulta", "Fornecedor")">Consultar Fornecedores</a></li>
                            <li><a href="@Url.Action("Lista", "Fornecedor")">Listar Fornecedores</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Produtos<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Cadastro", "Produto")">Cadastrar Produto</a></li>
                            <li><a href="@Url.Action("Consulta", "Produto")">Consultar Produtos</a></li>
                            <li><a href="@Url.Action("Lista", "Produto")">Listar Produtos</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    @RenderBody()
</body>
</html>

Estoque.Web/Areas/Admin/Views/Shared/_PartialLogin.cshtml
@using Estoque.DAL.Entity
@{
    if (Session["funcionariologado"] != null)
    {
        Funcionario f = (Funcionario)Session["funcionariologado"];

        <img src="/Imagens/@f.Foto" align="right" class="img-circle"
             width="90" height="90" />

        <div class="container">
            <div class="row">

                <label>Nome:</label> @f.Nome <br />
                <label>Login: </label> @f.Login <br />
                <label>Data de Cadastro: </label> @f.DataCadastro

            </div>
        </div>
    }
}