Estoque.Web/Models/Funcionario/FuncionarioModelCadastro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Estoque.Web.Models.CustomValidators;

namespace Estoque.Web.Models
{
    public class FuncionarioModelCadastro
    {
        [Required(ErrorMessage = "Por favor, informe o nome do funcionário.")]
        [Display(Name = "Nome:")]
        public string Nome { get; set; }

        [LoginDisponivel(ErrorMessage = "Erro. Este Login já encontra-se em uso.")]
        [Required(ErrorMessage = "Por favor, informe o login de acesso.")]
        [Display(Name = "Login:")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Por favor, informe a senha de acesso.")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha:")]
        public string Senha { get; set; }

        [Required(ErrorMessage = "Por favor, confirme a senha de acesso.")]
        [Compare("Senha", ErrorMessage = "Por favor, confirme a senha de acesso.")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirme sua Senha:")]
        public string ConfirmaSenha { get; set; }

        [UploadFoto(ErrorMessage = "Erro. Envie apenas imagens JPG de até 1MB.")]
        [Required(ErrorMessage = "Por favor, envie sua foto.")]
        [Display(Name = "Envie sua Foto:")]
        public HttpPostedFileBase Foto { get; set; }
    }
}

Estoque.Web/Models/Funcionario/FuncionarioModelLogin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Estoque.Web.Models
{
    public class FuncionarioModelLogin
    {
        [Required(ErrorMessage = "Preencha o campo Login.")]
        [Display(Name = "Login:")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Preencha o campo Senha.")]
        [DataType(DataType.Password)]
        [Display(Name = "Senha:")]
        public string Senha { get; set; }

        [Display(Name = "Manter conectado.")]
        public bool ManterConectado { get; set; }
    }
}

Estoque.Web/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Estoque.Web.Models;
using Estoque.DAL.Entity;
using Estoque.DAL.Persistence;
using Estoque.Util.Security;
using System.Web.Security;


namespace Estoque.Web.Controllers
{
    public class FuncionarioController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();

            Session.Remove("funcionariologado");
            Session.Abandon();

            return View("Login");
        }

        public ActionResult Cadastro()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CadastrarFuncionario(FuncionarioModelCadastro model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    Funcionario f = new Funcionario();
                    f.Nome = model.Nome;
                    f.Login = model.Login;
                    f.Senha = Criptografia.GetMD5Hash(model.Senha);
                    f.DataCadastro = DateTime.Now;
                    f.Foto = Guid.NewGuid().ToString() + ".jpg";

                    FuncionarioDal d = new FuncionarioDal();
                    d.Insert(f);

                    model.Foto.SaveAs(HttpContext.Server.MapPath("/Imagens/" + f.Foto));

                    ModelState.Clear();

                    ViewBag.Mensagem = "Funcionario " + f.Nome + ", cadastrado com sucesso.";
                }
            }
            catch (Exception e)
            {
                ViewBag.Mensagem = e.Message;
            }

            return View("Cadastro");
        }

        [HttpPost]
        public ActionResult AutenticarFuncionario(FuncionarioModelLogin model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    FuncionarioDal d = new FuncionarioDal();
                    Funcionario f = d.Authenticate(model.Login, Criptografia.GetMD5Hash(model.Senha));

                    if(f != null)
                    {
                        FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(f.Login, model.ManterConectado, 5);
                        HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(ticket));
                        Response.Cookies.Add(cookie);

                        Session.Add("funcionariologado", f);

                        return RedirectToAction("Index", "Default", new {area = "Admin"});
                    }
                    else
                    {
                        ViewBag.Mensagem = "Acesso Negado.";
                    }
                }
            }
            catch (Exception e)
            {
                ViewBag.Mensagem = e.Message;
            }
            return View("Login");
        }
    }
}

Estoque.Web/Views/Funcionario/Cadastro.cshtml
@model Estoque.Web.Models.FuncionarioModelCadastro

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cadastro</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />

</head>
<body>
    <br />
    <br />
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-4 col-md-offset-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Cadastro de Funcionários
                    </div>

                    @using (Html.BeginForm("CadastrarFuncionario", "Funcionario", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()


                        <div class="panel-body">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            @Html.LabelFor(model => model.Nome)

                            @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                            <br />

                            @Html.LabelFor(model => model.Login)

                            @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
                            <br />

                            @Html.LabelFor(model => model.Senha)

                            @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
                            <br />

                            @Html.LabelFor(model => model.ConfirmaSenha)

                            @Html.EditorFor(model => model.ConfirmaSenha, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ConfirmaSenha, "", new { @class = "text-danger" })
                            <br />

                            @Html.LabelFor(model => model.Foto)

                            <input type="file" name="Foto" />
                            @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
                        </div>

                        <div class="panel-footer">
                            <input type="submit" value="Cadastrar Funcionário" class="btn btn-success btn-block" />
                        </div>
                        
                    }
                    <div>
                        @ViewBag.Mensagem
                    </div>
                </div>
                <a href="/Funcionario/Login">Voltar</a>
                <hr />
            </div>
        </div>
    </div>
</body>
</html>

Estoque.Web/Views/Funcionario/Login.cshtml
@model Estoque.Web.Models.FuncionarioModelLogin

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />

</head>
<body>
    <br />
    <br />
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-4 col-md-offset-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        Sistema de Estoque
                    </div>

                    @using (Html.BeginForm("AutenticarFuncionario", "Funcionario", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="panel-body">

                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control", @placeholder = "Login" } })
                            @Html.ValidationMessageFor(model => model.Login, "", new { @class = "text-danger" })
                            <br />

                            @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control", @placeholder = "Senha" } })
                            @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })

                        </div>

                        <div class="panel-footer">
                            <input type="submit" value="Entrar" class="btn btn-success btn-block" />
                            <br />

                            <a href="/Funcionario/Cadastro" class="text-center new-account" style="float: right;">Cadastrar Funcionário</a>

                            @Html.CheckBoxFor(model => model.ManterConectado)
                            @Html.LabelFor(model => model.ManterConectado)

                        </div>
                    }

                </div>

                <div>
                    @ViewBag.Mensagem
                </div>
            </div>
        </div>
    </div>
</body>
</html>